### ISSUE TITLE
Interest for a Lite GTFS-TripUpdates

### ISSUE THREAD

**Issue by LeoFrachet** [google/transit#107]
Hi GTFS community!

Who (among both GTFS producers and consumers) would be interested into having a "Lite" GTFS-TripUpdate format, which would allow to call for the ETA for only one stop and one stop route.

It would be calling something like `http://example.com/tripupdate.pb?route_id=ri1&stop_id=si1`, and would contain only the StopTimeUpdate applying for this stop and route?

Why?
- For GTFS Producers: Currently providing GTFS-TU is a huge (& expensive) change for agency. They can do it only when there is a big RFP going out, and they cannot just add a converter at the output of their existing tools, since GTFS-TU requires the state of the whole system. Allowing a Lite GTFS-TU as described above would strive the adoption of the GTFS language in the real-time world.
- For GTFS Consumers: It would allow them to parse fewer different formats, and to push agencies to provide a standard and open source format.
- For the open source community: this allows to make converters from other format to Lite GTFS-TU (those formats could be standards like SIRI, or proprietary formats outputted by real-time providers)

Downsides?
- On the short term it would be a win, since we would have more GTFS-TU.
- On the long term it would be a win, because it would increase the momentum around GTFS-TU.
- On the mid-term though, it might be a small loose, because some agency could postpone the adoption of full GTFS-TU because they have a middle ground.

Thoughts? Especially big real-time consumers (@anatolip-rt, @gcamp, @slai, @TeXitoi, @Tristramg).

**Comment by TeXitoi** [comment]
@prhod

**Comment by barbeau** [comment]
Food for thought - MTA in NYC provides a GTFS-realtime feed for a snapshot of their entire bus system data.  However, they wanted to implement a RESTful API so mobile app developers could create apps without have to stand up a server, and to do this they chose SIRI (http://bustime.mta.info/wiki/Developers/SIRIIntro).  

From the above link:
>Unlike GTFS and GTFS-RT, SIRI objects include layers of elements that are primarily designed to provide small pieces of information. SIRI can be thought of as a menu; having picked a few items from that menu, we feel the results are simple and legible, if a bit verbose.

My understanding is that they wanted a standards-based solution, and SIRI was the only format that met this requirement.  What Leo is mentioning above would have given MTA a choice to use GTFS-realtime instead.

One other consideration is that as an app developer, you need access to the schedule data too to know where stops are, etc., and ideally you don't want to set up a server for this either.  MTA at one point was pursuing getting these schedule "discovery APIs" added to the SIRI standard.  So, we if do GTFS-realtime Lite (or whatever we call it), we should consider GTFS Lite too.

Historical references to past related Google Group discussions:
* [GTFS-Realtime vs. REST/XML](https://groups.google.com/forum/#!topic/gtfs-realtime/oCX7BxLE1A8)
* [Transit Data REST standards](https://groups.google.com/forum/#!topic/transit-developers/hjEVYCUyZmo)

**Comment by skinkie** [comment]
If this kind of thing would come in place and instead of the full view, this is a very bad idea. If this would be a full view, with only one prognosis at a stop, I fail to see how it would be incompliant with the current GTFS-RT TripUpdates.

Anyway if a per vehicle delay is really what the agency wants to communicate. Enhancing VehiclePositions with a delay field is much closer to SIRI-VM, and not a middle ground. Since Google Transit seems to prefer vehicle positions over trip updates, I would rather skip the 'lite' step here.

Proposal.
http://gtfs.openov.nl/gtfs-rt/gtfs-realtime-OVapi.proto

**Comment by gcamp** [comment]
I feel I didn't thought enough about it to give a definite opinion but I also feel it's a bad idea. 

Is there any good reason why SIRI is not a good API used with a static GTFS? I feel GTFS-rt should be good at what it's intended to do : real time for trip planning and having the full state of the system. There are other good standards for other uses. 

My impression is also that since GTFS-rt and GTFS-rt light will be used in significantly different ways that the code re-use argument exists but is not interesting enough.

**Comment by laidig** [comment]
Implementer of said MTA Bus Time SIRI spec here. 

SIRI in the Americas has been hampered by:
1. its complexity and verbosity;
2. lack of freely available and easily digestible documentation which spells out things like RESTful parameters for a fully compliant implementation;
3. lack of standardized mapping to the GTFS; and
4. lack of vendor, industry group, and government support.

We did a fair bit of shoe-horning for 2 and 3 (this was before v2.0 which clarified RESTful implementations), and I've since come to find that even then there were some non-compliant choices made (the perils of XML tooling).

I'm not 100% on board for the idea of GTFS-rt-lite, [because](https://www.xkcd.com/927/), but it could easily solve 1,2, and 3. 4 would have to come from this group.

**Comment by prhod** [comment]
Speaking for Kisio (with @TeXitoi and @kinnou02) , we don't feel comfortable with the proposal.  
The strength of the GTFS-realtime is the capacity to update efficiently all the stop times of a batch of trips.
Providing a GTFS-TU Lite for one stop and one route will imply an API system instead of a full data dump, and a client will have to download the full GTFS Dataset to be able to use this API and provide form example the route_code of the trip (as stated by @barbeau and @skinkie).
We also agree with @gcamp that a SIRI Lite API is an already availabel format for a client to provide next departures at a stop with the needed context for a direct display.

I'm not convinced with the short term win about having more GTFS-TU, because we would have two distinct TripUpdates (the one with only one StopTimeUpdate, and the other one).

**Comment by abyrd** [comment]
I see this has been closed but would just like to add one more data point. If I'm understanding you correctly, the difference between existing GTFS-RT and the proposed "lite" GTFS-TripUpdate format is that you would fetch one stop at a time via an API rather than transferring the whole system state.

This is more than a simple change in data format, it's a fundamental change to the purpose and delivery mechanism of GTFS-RT. Feeding information on request to end users is quite a different application than transferring bulk information between backend components. So there are two aspects to this proposal: reworking the data format to allow per-stop information, and a whole new request-response mechanism at a different layer, essentially outside GTFS-RT.

I agree with most of the critical responses above, and think this is probably not a good idea. There are other existing specifications for fetching data stop by stop, and the people who maintain the SIRI spec went to extra effort to officially accommodate the REST/JSON based variant they saw emerging in New York. 

I would also question the assertion that the producers "cannot just add a converter at the output of their existing tools". I was under the impression that One Bus Away is able to receive real time data piece by piece and aggregate it into a full system state that is exported as GTFS-RT (streaming in my experience but I would imagine it also supports file dumps).

As a side note, I would be cautious of using the terminology 
"light" in this context, since I've heard several people using/designing the SIRI spec use "light" to mean REST+JSON API instead of SOAP+XML API. This is quite different than your distinction here of single-stop API vs. full transfer of system state.

**Comment by barbeau** [comment]
>I would also question the assertion that the producers "cannot just add a converter at the output of their existing tools". I was under the impression that One Bus Away is able to receive real time data piece by piece and aggregate it into a full system state that is exported as GTFS-RT (streaming in my experience but I would imagine it also supports file dumps).

Aggregating a GTFS-rt feed from a REST API source has been done, but it's messy from two perspectives:
* IDs matching GTFS - if you're trying to build a GTFS-rt feed, you need to reference the IDs from GTFS (trip_id, stop_id, etc.).  These IDs aren't always exposed via the REST API because typically it wasn't built with GTFS in mind.  This "external IDs" issue is a point that has repeatedly come up in the past, and we're working on a proposal for this separately.  However, it would be better if this issue didn't exist in the first place.  By having a conceptual representation of GTFS in a REST API, it gives producers a direct way to link the two datasets via IDs.
* API rate limits - To assemble a full GTFS-rt TripUpdates feed, you need to query a REST API for every single arrival at every single stop in the system.  For reasonably-sized system, and depending on how the API is structured, this can result in a large number of very frequent API calls.

I'm not necessary advocating for this concept as I agree with many of the limitations discussed above, but I just wanted to provide the above info.

**Comment by abyrd** [comment]
> On 8 Nov 2018, at 01:15, Sean Barbeau <notifications@github.com> wrote:
> Aggregating a GTFS-rt feed from a REST API source has been done, but it's messy from two perspectives:
> 
I may have misunderstood something - I was referring to accumulating a continuous stream of realtime events from active vehicles for redelivery as GTFS-RT or as a REST API, not accumulating information scraped from a REST API. If they already have a REST API I would expect there to be such an event stream somewhere behind it. But I suppose this is where the “legacy closed systems” problem comes in.
> API rate limits - To assemble a full GTFS-rt TripUpdates feed, you need to query a REST API for every single arrival at every single stop in the system. For reasonably-sized system, and depending on how the API is structured, this can result in a large number of very frequent API calls.
I was definitely not advocating this, it sounds very inefficient.
