### ISSUE TITLE
Should we vote also before beta implementation?

### ISSUE THREAD

**Issue by LeoFrachet** [google/transit#150]
Hi GTFS community!

As you know, to open the vote on a proposal, we currently need:
- a proposal
- a producer, producing a GTFS which uses the proposal
- a consumer, consuming GTFSs which uses the proposal 

Some stakeholders complain that they have to implement new feature before having the proposal being voted. I think we should still wait to have producer & consumer to add to the core spec, but maybe we could have another vote, a kind of "vote on proposal", which would show that the community agrees on the current version, and that stakeholder can start considering implementations.

What are your thoughts on that?

**Comment by skinkie** [comment]
Good point, in Dutch transit standardisation we have recently oped in for a reference implementation from consumer side to validate that what producers are creating actually is valid and extensions make sense. The same could obviously go for a producer side. Now the question is: could you make a GTFS reference implementation that has the principle target to be a QA-suite but still get the same developer love as a public facing application would receive. To have a reference implementation to work, we would have to work out some architecture and transparent libraries that everyone would agree on, liberally licensed so nobody could complain, and potentially a funded development for it.

The problem I have with not providing something that proves that a proposed idea works, and is trivial to add, is that we organically grow a standard which because of earlier backwards compatibility choices would never be revised.

**Comment by skinkie** [comment]
Keep open.
