### ISSUE TITLE
Occupancy status during Covid-19

### ISSUE THREAD

**Issue by antrim** [google/transit#222]
**Issue:** During the Covid-19 epidemic, most transit agencies are limiting occupancy to enable social distancing. All of the 7 enum values of the [OccupancyStatus field](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/vehicle-positions.md#occupancy-status) in the VehiclePositions feed **do NOT** apply in this case:
- EMPTY
- MANY_SEATS_AVAILABLE
- FEW_SEATS_AVAILABLE
- STANDING_ROOM_ONLY
- CRUSHED_STANDING_ROOM_ONLY
- FULL
- NOT_ACCEPTING_PASSENGERS

@MobilityData proposes that agreement on an industry best practice to enable clear messaging during Covid-19.

**Best practice proposal, for discussion:** 
(Edit, May 5: This is not meant to be a permanent change to the specification but temporary guidance while revisions the the occupancy field are discussed. See #212).
OccupancyStatus enum values would reflect safely available seats (**NOT** the maximum seating capacity of the vehicle). The OccupancyStatus enum values used during Covid-19 social distancing would be limited to 3, and refer to the seats available for safe occupancy, not maximum physical capacity (edited):
- MANY_SEATS_AVAILABLE
- FEW_SEATS_AVAILABLE
- FULL (This would indicate the vehicle is at it's designated maximum capacity for social distancing.)

**Justification:**
- Many stakeholders proposed reducing the number of enum values in issue https://github.com/google/transit/pull/212#issuecomment-611667724.
- Whether a bus has **_many seats available_** or is **_empty_** would have the same consequence to travelers.
- Most APC systems may not be able to determine with precision if a bus is empty or nearly empty. Plus, there are no reports of the _empty_ value being used in GTFS-realtime feeds.
- **_Standing room only_** and **_crushed standing room only_** would not apply during Covid-19.
- No feeds include **_not accepting passengers_**.

Thoughts?

**Comment by Bertware** [comment]
In my opinion this is a client-side issue, and clients (apps getting data from some GTFS source and showing something to a traveller) should decide how they handle this. Maybe they can show everything from `STANDING_ROOM_ONLY` to `FULL` as `FULL`, or maybe they just go on showing everything like it was before (meaning travellers know what to expect on which occupancy level). It is up to clients/consumers to interface with the travellers, the only task for producers is to produce stable, consistent high quality feeds. I'm against changing up the spec/best practices because there are some regional changes in travel advice for a couple of months.

> during Covid-19 social distancing

- When does this end?
- Does it end all of a sudden or gradually? If gradually, when has it really ended?
- Are these the exact same datums in the entire world?

A local client can adapt to local needs, a local producer can maybe do it, but a single simple spec/best practice making everyone do the same for the entire world is not the solution for this.

**Comment by antrim** [comment]
This isn't meant to be a permanent change to the specification, rather a proposal for a temporary industry agreement while Occupancy Status v2 (#212) is sorted out.

As @Bertware points out, there is not a way of specifying rule and procedure changes for distancing in GTFS. Perhaps in the future, a combination of physical capacity information provided in GTFS-Vehicles (#200) and a new occupancy field, say "AllowedOccupancy" would clearly specify when there is a policy-based occupancy limitation. Coming to agreement around these changes will take time.

At issue right now is how consumers and producers should both interpret the specification. Does "Many Seats Available" available refer to physical capacity or allowed capacity? What would "Standing Room Only" mean if a distancing policy is in effect; should an agency put that in their data? In the absence of data that indicates whether a distancing policy is in effect, do feed consumers need to research the distancing policies of all agencies providing OccupancyStatus, and factor that into the display?

Given all the ambiguity these questions present, and the time it will take to create and vote on a more comprehensive change to how occupancy is expressed, I think it would likely be useful to see some convergence of practice around temporary standardized practices. Responding to the pandemic is taking a certain amount of step-by-step experimentation around the world.

**Comment by devadvance** [comment]
Coming from an end-user perspective at this time: wouldn't it be more direct and unambiguous to use the `occupancy_percentage` added in #213 for this purpose? Within a given passenger vehicle, the effect of social distancing is a reduction in passenger density. In other words, "are more people allowed within this space?"

An analogous implementation already in effect might be a grocery store: the number of carts or baskets in use is a proxy for the real metric, which is the number of individuals permitted in the store at any given point in time.

Similarly, the type of space available (seating, standing room, etc.) isn't critical in answering that question. A vehicle could have "few seats available" because there were only five seats per 20m^s to begin with.

**Comment by antrim** [comment]
@devadvance : I agree, `occupancy_percentage` is better for this. @gcamp added a statement that the percentage occupancy is as per "current operating regulations allow" (https://github.com/google/transit/pull/213/commits/c1a297ab73fe4bcebc2740d70472ad7c0c47474d). So that offers clarity during social distancing.

`occupancy_percentage` is better suited, but I wonder if there are some consumers and producers that won't be able to implement this immediately.

**Comment by botanize** [comment]
> Coming from an end-user perspective at this time: wouldn't it be more direct and unambiguous to use the `occupancy_percentage` added in #213 for this purpose? 

I strongly disagree. The problem with `occupancy_percentage` is that no one knows what the baseline is, even if the spec states "current operating regulations". If you tell me 80% I would have to know that the vehicle coming is a 40 foot vehicle with 36 seats and a current maximum safe capacity of 10 passengers to know that I have a small chance of getting on. But if instead it's a 60 foot vehicle with no restrictions I could easily board. Whereas "FEW_SEATS_AVAILABLE" tells me exactly that without needing to know anything about the vehicle, its stated capacity, or the current restrictions that may be in place.

**Comment by paulswartz** [comment]
@mbta has decided on the following:

- `MANY_SEATS_AVAILABLE`: publicly displayed as "Not crowded"
- `FEW_SEATS_AVAILABLE`: "Some crowding"
- `FULL`: "Crowded"

Our website and API documentation reflect these categories, and we've worked with @gcamp / Transit App to have them display the categories this way as well.
