### ISSUE TITLE
Incorporate feed_version in GTFS-RT FeedHeader

### ISSUE THREAD

**Issue by skinkie** [google/transit#255]
It has brought to my attention that at this moment GTFS-static feed_version is unmatched in GTFS-RT. At this moment it merely an assumption that both actually match. I would propose to extend the GTFS-RT FeedHeader with a feed_version field. If the feed_version within GTFS-RT is higher than GTFS-static the realtime client must update their schedules. 

https://developers.google.com/transit/gtfs-realtime/reference#message-feedheader

**Comment by timMillet** [comment]
Hi Stefan,

I think it’s a very good idea. The main use case I see in favor of this is to reduce as much as possible the time gap during which consuming apps are not able to show real-time information anymore (e.g: when the `trip_id` values from TripUpdate refers to new `trip_id` values of a new schedule dataset that has not been ingested yet).

However, I have some concerns incorporating the GTFS `feed_info.feed_version` in GTFS-RT FeedHeader, because the GTFS `feed_info.feed_version` definition is relatively vague and because of this, it can be used different manners by data producers:
- It’s a text field so it’s ambiguous to know when its value is “higher” so that it indicates to the data consumer to update their schedules.
- It’s not defined as dataset unique so its value can remain the same across different iterations (e.g: `feed_version=Winter 2021` for each weekly iterations of the dataset)

So I’d suggest either refining the definition of `feed_info.feed_version` to better frame its use (but it may not be backward compatible), or creating a new field (e.g: `feed_info.feed_version_number`) that could be a non negative integer with a requirement that its value must increase along the dataset iterations. Then we could incorporate `feed_info.feed_version` with its updated definition or the new field in GTFS-RT FeedHeader.

What are your thoughts on this?

**Comment by skinkie** [comment]
Keep open.

**Comment by derhuerst** [comment]
This is still relevant, please reopen.
