### ISSUE TITLE
Can stop_times reference stops with location_type = 3 or 4?

### ISSUE THREAD

**Issue by mmorang** [google/transit#257]
The current documentation for the stop_id field in stop_times.txt says "Referenced locations must be stops, not stations or station entrances."  It seems this has not been updated since location_type 3 (Generic Node) and 4 (Boarding Area) were added.  If I had to guess, I would say it should not be allowed for stop_times to reference generic nodes and boarding areas, but I think this should be clarified and made explicit in the documentation for stop_times.

I cannot make a PR in this repo without extensive bureaucratic hassle from my company, so it would be wonderful if someone else could take on this task.

**Comment by skinkie** [comment]
@mmorang agreed. But I guess it should also be made clear we are mixing 'the infrastructure' with 'the transit network' here. I know (many) producers, including myself who would at least have the ability to schedule on stations, which is not allowed, since only stops are allowed. This leads to the introduction of 'virtual stops' representing the station. If we make clear what things in stop_times can be used, we might want to do so for things such as transfers as well.

**Comment by timMillet** [comment]
@mmorang 
Hi Melinda,
Effectively, stop times cannot reference stops with `stops.location_type=3` or `=4`. I made the PR (https://github.com/google/transit/pull/258) you requested! You will note that I removed the mentions of the other location types -it explicitly tells what _must_ be done only- so that the definition will not need to be changed again if new location types are added in the future. Please review it and tell me if you agree!

@skinkie
Hi Stefan,
I agree there is a need for debating on the ability to schedule on stations, i.e referencing in `stop_times.stop_id` stops with `stops.location_type=1`. I did not include this ability in the PR though, as it would be an extension of the specification and not only a clarification. If you want, I'd suggest opening a dedicated issue, as the title of this current issue could be confusing for other community members.
