### ISSUE TITLE
Addition of timepoint field to stop_times.txt not logged in revision history

### ISSUE THREAD

**Issue by CharlesBelov** [google/transit#264]
The [current documentation for stop_times.txt](https://developers.google.com/transit/gtfs/reference#stop_timestxt) includes the field timepoint.

However, the only mention of timepoint in the [revision history](https://developers.google.com/transit/gtfs/guides/revision-history) is:

February 2, 2015

    Added the proposal for timepoint to stop_times.txt on the Reference page. For details, read the discussion.

There also needs to be an entry for when the timepoint field was added to stop_times.txt. Please add.

**Comment by barbeau** [comment]
@CharlesBelov That Google Group discussion linked to in that revision history entry is the correct official proposal for adding `timepoint` to `stop_times.txt`. The GTFS spec wasn't on GitHub yet at that time so there isn't a pull request to link to for that proposal.

**Comment by scmcca** [comment]
On this matter, there is a more general problem of the revision history not being consistently updated or maintained.

As I understand, the revision history was useful for tracking changes before the GTFS spec was moved to GitHub on March 16, 2016 ([source](https://github.com/google/transit/blob/master/gtfs/CHANGES.md#march-16-2016)), and has been inconsistently updated since. I contributed an update to fill in missing entries [some time ago](https://github.com/google/transit/pull/225), but did this by consulting the GitHub feature that automatically tracks changes. 

I think what this reveals is that updating the revision history past March 16, 2016 is redundant and evidently, often overlooked (e.g., it is not a built-in requirement in the specification amendment process).

I drafted a branch of some changes [here](https://github.com/google/transit/compare/master...MobilityData:ammend-revision-history) that proposed to discontinue the assumed maintenance of the revision history. The branch removes all entries of the revision history past March 16, 2016 and directs the user to the location on GitHub where they are tracked by default.

I'm wondering if others think this would be a good idea to clean up this loose end and if it's worth putting that branch to a PR. Looking forward to feedback (I can always open another issue to address this, I don't mean to takeover this conversation!).
