### ISSUE TITLE
Wheelchair accessible and bike allowed best practices

### ISSUE THREAD

**Issue by mpaine-act** [google/transit#270]
What is the best practices for an operator to provide this information, when they know all of their vehicles allow wheelchairs and bicycles but don't know the status of any stops?   Is it best to set both trips.txt and stops.txt wheelchair_accessible and bikes_allowed to 0, or is it better to set trips.txt to 1 and stops.txt to 0 for both?

**Comment by scmcca** [comment]
The best practice would be for the agency to know which of their own stops are wheelchair accessible. 

But, from the scenario you described, `trips.wheelchair_accessible` and `.bikes_allowed` should be set to `=1`, since the spec description holds true:

> Vehicle being used on this particular trip can accommodate at least one rider in a wheelchair / bicycle.

Meanwhile, `stops.wheelchair_boarding` should `=0` since there is no accessibility information for any of your stops in particular. Important to note that "no accessibility information" does not mean "not accessible".

Finally, the implied `stops.bikes_allowed` is not a field defined in the spec.

This is my interpretation of the spec. Open to other thoughts!
