### ISSUE TITLE
Remove stale-bot

### ISSUE THREAD

**Issue by skinkie** [google/transit#292]
It annoys me too much.

**Comment by Cristhian-HA** [comment]
Hello Stefan, I really appreciate your concern regarding the stale bot, however since we just configured this for issues it might feel like the notifications are a bit annoying right now. As you know we have a lot of historical stale issues that have been open for more than a year and we want to make sure that we only keep open the relevant ones. This process won't last long, because after all stale conversations will be cleared, those notifications will be less and less present. The configuration for the stale bot is to send a notification when there is a stale issue for at least 365 days and it will be closed after 14 days, we have done this for all the PR’s and it went well. Please let me know if you still have some concerns. Happy Friday!

**Comment by skinkie** [comment]
The problem remains with pull requests that are closed.

**Comment by scmcca** [comment]
@skinkie Pull requests are closed based on an automation of the [Specification Amendment Process](https://github.com/google/transit/blob/master/gtfs/CHANGES.md), which states in article 8 that:

> Any pull request remaining inactive for 30 calendar days will be closed. When a pull request is closed, the corresponding proposal is considered abandoned. The advocate may reopen the pull request at any time if they wish to continue or maintain the conversation.

**Comment by Cristhian-HA** [comment]
Hello @skinkie the initial mess of stale issues has stabilized. Now the community has a clearer view on which open issues matter to them; this will concentrate our focus. We won’t be getting any more stale issue notifications for another year at minimum.
With that, I think this issue is resolved. May we close?

**Comment by skinkie** [comment]
Ok, lets close...
