### ISSUE TITLE
Case-sensitivity of filenames

### ISSUE THREAD

**Issue by Tristramg** [google/transit#297]
The specifications says that the columns names are case-sensitive.

However nothing is specified for filenames. Should a `Routes.txt` be a valid file for the routes or not.

I have no strong opinion here, but I believe the specification should be explicit if can be allowed or not.

**Comment by skinkie** [comment]
I (hoped) it was explicit from all the examples. But I guess you have found a producer that uses capitals?

**Comment by Tristramg** [comment]
I was also obvious for me ;)
But indeed, a producer came with a capital, and we can’t really point to
paragraph of the specification

**Comment by scmcca** [comment]
We can add it as a point to the "File Requirements" section. Perhaps we can amend the 3rd point to say:

> All file and field names are case-sensitive.

**Comment by Tristramg** [comment]
Seems good for me. What would be the following steps to actually amend that point?

**Comment by skinkie** [comment]
> Seems good for me. What would be the following steps to actually amend that point?

Think you want to create a pull request, with an immediate vote, and announce it on the mailinglist.

**Comment by scmcca** [comment]
@Tristramg Please see the [specification amendment process](https://github.com/google/transit/blob/master/gtfs/CHANGES.md). 

AFAIK immediate votes are not the norm when opening a pull request (usually 7 days of discussion are needed first). Also voting can only be called by the advocate of the pull request.

At any rate, I almost think we can merge this one directly since it is a fairly minor and straightforward clarification?
