### ISSUE TITLE
Changes to fare_transfer_rules.fare_transfer_type

### ISSUE THREAD

**Issue by omar-kabbani** [google/transit#307]
# Changes to fare_transfer_rules.fare_transfer_type

This GitHub issue was raised in response to a discussion in [pull Request #286](https://github.com/google/transit/pull/286), and has been prioritized by MobilityData, who is going to work on it with the agenda described below.

## The need
The specification should be human readable and flexible.

## The issue

 - Stakeholders have flagged that the wording of the enumerations in `fare_transfer_rules.fare_transfer_type` is not very intuitive
 - The current enumerations in `fare_transfer_rules.fare_transfer_type` may not cover all the industry use cases 
 
## Potential options
- Option 0: Leave as-is
	- Pros: Lighter specification with fewer fields, ability to expand with additional fields by adding enumerations instead of fields
	- Cons: Makes the field definition of `fare_transfer_rules.fare_transfer_type` dense
- Option 1: Remove the field `fare_transfer_rules.fare_transfer_type` and replace with four new fields
	- `include_previous_fare_leg_rule_amounts`: enum 0, 1
	- `include_previous_fare_transfer_rule_amounts`: enum 0, 1
	- `include_next_fare_leg_rule_amount`: enum 0, 1
	- `include_most_expensive_fare_leg_rule_amount`: enum 0, 1
		- Pros: Allows for maximum flexibility through using different field combinations 
		- Cons: Adds three new fields to the specification. More fields might be added if additional use cases are required. 

An analysis of the possible combinations using option 0 vs option 1 is presented below:

A corresponds to the fare for the first leg
B corresponds to the fare for the second leg
AB corresponds to the transfer cost

The table below demonstrates that while option 1 (using different fields) provides more flexibility and can represent more use cases, these additional use cases are not logical and do not describe practical use cases. Option 0 (enumerations) can represent all the logical combinations from option 1. 

| |incl A |incl AB|incl B|incl max(A,B)|Result|Logical use case?|Representation using current implementation|
|--|--|--|--|--|--|--|--|
|Combination 1| YES |YES|YES|YES|A+AB+B+MAX(A,B)|No||
|Combination 2| YES |YES|YES|NO|A+AB+B|Yes|enum 1|
|Combination 3| YES|YES|NO|YES|A+AB+MAX(A,B)|No||
|Combination 4 |YES |YES|NO|NO|A+AB|Yes|enum 0|
|Combination 5| YES |NO|YES|YES|A+B+max(A,B)|No||
|Combination 6| YES |NO|YES|NO|A+B|Yes|enum 1 (amount=0)|
|Combination 7 | YES |NO|NO|YES|A+MAX(A,B)|No||
|Combination 8 |YES |NO|NO|NO|A|Yes|enum 0 (amount=0)|
| Combination 9 | NO |YES|YES|YES|AB+B+MAX(A,B)|No||
|Combination 10 | NO|YES|YES|NO|AB+B|Yes*|enum 1 (amount=AB-A)|
|Combination 11 | NO |YES|NO|YES|AB+MAX(A,B)|Yes|enum 2|
|Combination 12 | NO |YES|NO|NO|AB|Yes|enum 3|
|Combination 13 | NO |NO|YES|YES|B+MAX(A,B)|No||
|Combination 14 | NO |NO|YES|NO|B|Yes*|enum 1 (amount=-A)|
|Combination 15 | NO|NO|NO|YES|MAX(A,B)|Yes*|enum 2 (amount=0)|
|Combination 16 | NO|NO|NO|NO|0|No||

*These combinations are possible, but correspond to unlikely use cases. 

## MobilityData's recommendations
MobilityData recommends implementing option 0 as it addresses the needs raised in this issue. With option 0, all the possible use cases can be modelled, additionally, the specification remains light, and any use cases which are not covered by the current implementation can be accounted for by extending the enumerations. 

2022-01-31: Issue opened on GitHub

### Phase 1
From 2022-01-31 to 2022-02-11 (10 business days): Conversations on GitHub with the community. 

### Phase 2
From 2022-02-14 to 2022-02-18 (5 business days): MobilityData will gather and analyze the feedback provided in phase 1, and will publish a summary by 2022-02-18.

### Phase 3
If the community was unable to reach consensus by the end of phase 1, MobilityData will call for three meetings to resolve any outstanding items regarding `fare_transfer_rules.txt`. Feel free to block the below times in your calendars:
Meeting 1: 2022-02-22 11:00 to 12:00 ET
Meeting 2: 2022-02-23 11:00 to 12:00 ET
Meeting 3: 2022-02-24 11:00 to 12:00 ET
Please reach out to specifications@mobilitydata.org to receive an invite or react to this message to receive a meeting invite. 

### Phase 4
From 2022-02-28 to 2022-03-04 (5 business days): MobilityData will gather and analyze the feedback provided in the phase 3, and will publish a summary by 2022-03-04.

### Phase 5
If consensus was reached, MobilityData will open the vote on the week of 2022-03-07, otherwise, MobilityData will act as a facilitator to help the community reach consensus through meetings, online conversations, or other appropriate means. The time period for this phase starts on 2022-03-07 and ends on 2022-03-11 (5 business days). MobilityData can be invited to take meetings notes or can be kept in Cc for those exchanges.

### Phase 6
From 2022-03-14 to 2022-03-19 (5 business days): MobilityData will gather and analyze the information shared during phase 5, and will publish a summary by 2022-03-19.

### Phase 7:
In all cases, the vote will be opened on the week of 2022-03-28. If the vote does not pass, MobilityData will end the work on these issues and will inform the community. This will not prevent other stakeholders from continuing the effort to drive the adoption of the base implementation of GTFS-Fares.

**Comment by flocsy** [comment]
I would also add to the Pros of Option 1: more clarity

I don't see why the cases you specified as possible but unlike: AB+B, B, MAX(A,B) are very likely.

The most important thing in the table are the strained amount values you would have to use to be able to "puzzle out" the right total amount. But if I know what's the right total amount then I don't need GTFS Fares v2 :) It's not logical to say: enum 1 (amount = -A). This is not a math class, people who write the gtfs "translate" the reality (complex as it might be) to csv lines. In Sydney amount=-2 makes sense because it's a $2 discount. Negative amounts for the purposes you used are not logical. And amount=AB-A is a bad joke.

But the biggest problem of this proposal is that it only tries to fix the 2 leg problem, and the real issue that is N-leg problem. This proposal it useless even in case of 3 legs, not to mentione any more.

**Comment by omar-kabbani** [comment]
Thanks for the quick and thorough feedback - 
I've broken down the response into three pieces:

> But the biggest problem of this proposal is that it only tries to fix the 2 leg problem, and the real issue that is N-leg problem. This proposal it useless even in case of 3 legs, not to mentione any more.

The field definition of fare_transfer_type outlines how multi-leg transfers are handled, I've pasted a screenshot from the [reference documentation](https://github.com/google/transit/pull/286/files#diff-3ecf0760eb54b4953728042a1e30586705dc2335807be94faae0de5829cd12a1). 

![image](https://user-images.githubusercontent.com/78552622/152253164-3348c9e6-c14e-4f1f-a4be-9fa752efcaab.png)
  
Essentially, the transfer cost accounts for the costs incurred in previous legs, and then passes on the costs in the next transfer depending on the enumeration. In the above screenshot, S corresponds to the accumulated costs of the previous legs and transfers.  

Here's an example of how this might look like:
`fare_leg_rules.txt`

leg_group_id | from_area_id| to_area_id  | amount  |currency
|--|--|--|--|--|
A | area_1 | area_2 |  5|CAD  
B | area_2 | area_3 |  2|CAD
C | area_3 | area_4 |  4|CAD

`fare_transfer_rules.txt`

from_leg_group_id | to_leg_group_id|fare_transfer_type| amount  |currency
|--|--|--|--|--|
A | B | 0 | 1|CAD  
B | C | 1 |  -0.5|CAD

For a journey A → B → C:
A → B: The cost is A + AB = 5 + 1 = 6 CAD
B → C: The cost is S + BC + C = 6 -0.5 + 4 = 9.5 CAD 

So the entire journey costs 9.5 CAD

> Negative amounts for the purposes you used are not logical. And amount=AB-A is a bad joke.

If I were to give an example for a practical use case for `amount`=AB-A
Consider a case where trip A costs 5 CAD, and trip B costs 2 CAD. Transferring from A to B will incur a cost of 1 CAD, where riders who transfer from A to B will pay a transfer fare and the fare for B ,but will get their previous leg refunded.

leg_group_id | from_area_id| to_area_id  | amount  |currency
|--|--|--|--|--|
A | area_1 | area_2 |  5|CAD  
B | area_2 | area_3 |  3|CAD

The `fare_transfer_rules.amount` will be set to 0.5 - 5 = -4.5 

`fare_transfer_rules.txt`

from_leg_group_id | to_leg_group_id|fare_transfer_type| amount  |currency
|--|--|--|--|--|
A | B | 1 | -4.5|CAD  

Therefore, the journey cost will be 5 - 4.5 + 3 = 3.5 CAD. 

In the case of multi-leg transfers, it would look something like this 

leg_group_id | from_area_id| to_area_id  | amount  |currency
|--|--|--|--|--|
A | area_1 | area_2 |  2|CAD  
B | area_2 | area_3 |  5|CAD
C | area_3 | area_4 |  3|CAD

The `fare_transfer_rules.amount` will be set to 0.5 - 5 = -4.5 (which will refund B and incur a 0.5 CAD transfer fee)

`fare_transfer_rules.txt`

from_leg_group_id | to_leg_group_id|fare_transfer_type| amount  |currency
|--|--|--|--|--|
A | B | 1 | 1|CAD  
B | C | 1 | -4.5|CAD  

The first leg costs 2 + 1 + 5 = 8 CAD
The journey will cost S + BC + C = 8 - 4.5 + 3 = 6.5 CAD

> I don't see why the cases you specified as possible but unlike: AB+B, B, MAX(A,B) are very likely.

It's worth noting that if the current enumerations do not cover the industry's use cases - we can always extend it with additional enumerations.
As MobilityData, our position as a mediator is to facilitate constructive conversations within the community to move GTFS-Fares forward. We want to outline the pros and cons of the different proposals, but ultimately, we are happy with any solution that the community wants to adopt.

**Comment by omar-kabbani** [comment]
### Summary of roundtable discussions on `fare_transfer_type`
#### (22, 23, and 24 February 2022 11:00 AM ET)
---
Attended (partially or fully) by: @Cristhian-HA, @omar-kabbani, @flocsy, @jsteelz, @npaun, @philip-cline, @skinkie, @ritesh-warade-ibigroup, and @derhuerst

**Overview of the discussions:**
- Both approaches; using enumerations (current implementation) or using separate fields provide the same functionality to describe fare transfer types
-  Based on the discussion above, MobilityData is willing to proceed with whichever option the community agrees on
- A key point that needs to be clarified is the lookback period of the field `fare_transfer_type`
  - MobilityData recommends that the field only covers the decision regarding the current transfer. For multi-leg transfers, the current transfer cost will be added to the costs accumulated through earlier transfers (see example below)
  - In the base implementation, a lookback period beyond the current transfer is not possible. Arrangements - such as for a journey A→B→C→D→E, the fare for B will be free (reimbursed) - are not possible in the base implementation
  - This could be considered in future efforts especially with the fields `transfer_id` and `transfer_sequence`
- MobilityData sees that the current field definition for `fare_transfer_type` is enough to describe that the transfer type applies to the current transfer only (with the examples of S+BC+C etc.), however, we are open to further clarifying the definition if the current description is insufficient

We would like to hear whether the community believes the current implementation is sufficient, or if there are any changes to be made.

---

**Implementation example:** 

**`fare_leg_rules.txt`**
| `leg_group_id` |`from_area_id`  |`to_area_id`|`network_id`|`amount`|`currency`|
|--|--|--|--|--|--|
| A | areaA |areaB|bus|2|CAD|
| B | areaB |areaC|bus|0.5|CAD|
| C | areaC |areaD|bus|3|CAD|
| D | areaD |areaE|bus|1|CAD|
| E | areaE |areaF|bus|1.5|CAD|

**`fare_transfer_rules.txt`**
| `from_leg_group_id` |`to_leg_group_id`  |`amount`|`currency`|`fare_transfer_type`|`spanning_limit` | `duration_limit` | `duration_limit_type`|
|--|--|--|--|--|--|--|--|
| A | B |0.1|CAD|0|0|7200|0|
| B | C |0.2|CAD|1|0|7200|0|
| C | D |0.3|CAD|2|0|7200|0|
| D | E |0.5|CAD|3|0|7200|0|

The cost breakdown for a journey A→B→C→D→E is as follows: 

**A→B**
- Cost = fareA + transferAB
- Cost = 2 + 0.1 = 2.1 CAD

**B→C**
- Cost = S + transferBC + fareC
- Cost = 2.1 + 0.2 + 3 = 5.3 CAD

**C→D**
- Cost = S + MAX(C,D) + CD
- Cost = 5.3 + MAX(3,1) + 0.3 = 5.3 + 3 + 0.3 = 8.6 CAD

**D→E**
- Cost = S + transferDE
- Cost = 6.6 + 0.5 = 7.1 CAD

**Comment by flocsy** [comment]
@omar-kabbani I think you managed to demonstrate one of the problems when using "2-leg" rules on multi-leg journey:
The price of C was added twice in the total.

**Comment by omar-kabbani** [comment]
Good catch, I would say that is partly due to bad data and partly due to a limitation of the specification.

I used all four enumeration options in the above example just to demonstrate how they work in multi-leg transfers, but I believe that transit agencies would produce more realistic datasets.

It appears that `enum=2` is the problematic field when it comes to multi-leg transfers. Below is the field definition, under column "processing B > C", only `enum=2` includes fare B, which is the past fare, which could potentially double count a fare. 

![image](https://user-images.githubusercontent.com/78552622/156436737-deb8d8df-1784-46ed-bff1-08dd647f567c.png)


I see the use case for `enum=2`, but it probably is not as common as the other enumerations. I am in favor of keeping it as it must have been added because an agency requested it. Would adding a note/warning that this option might double count fares if fareB>fareC sort it out?

Aside from that, processing costs for multi-leg transfers could be improved if they are tied with `transfer_id` and `transfer_sequence` in future efforts.

**Comment by flocsy** [comment]
There's another problem with enum=2. It's not clear what S means: is it all the previous "leg fares" or "transfer fares" or both?
So maybe just for clarity we should split S to Sl + St (previous sum of leg fares vs previous sum of transit fares). Even if we keep it as is (meaning we just search&replace "S" with "Sl+St" for now, it will enable us adding more enums when there will be demand.

This will also fix the enum=2 MAX issue, because then we could have: enum 2: MAX(A,B) + AB | MAX(Sl, C) + St + BC

Another way to try to clarify the issue is to write the formulas differently:
0: A + SUM(T) (this also clarifies something that is not 100% clear in the original way, that we mean to include only the 1st leg's fare as opposed to include all leg's fare except the last leg's)
1: SUM(L) + SUM(T)
2: MAX(L) + SUM(T)
3: SUM(T)

**Comment by omar-kabbani** [comment]
> There's another problem with enum=2. It's not clear what S means: is it all the previous "leg fares" or "transfer fares" or both?

The spec defines S as:
<img width="510" alt="image" src="https://user-images.githubusercontent.com/78552622/158244421-cad180dd-786b-4857-9996-f380456997be.png">
So it's whatever the rider has paid in previous fares and transfers 

However, we are open to making the change to break S into SI and ST - @flocsy your example above certainly helps with `enum=2` and any future enumerations - if there are no objections I can proceed with the change

For the alternate way of writing the formulas, I would recommend we stick with the current implementation - the current approach is more "cumulative" as the fare is built depending on the rider's trip (so S changes depending on the previous legs/transfers)

**Comment by flocsy** [comment]
I don't think that adding such a note would solve anything. The problem is not that if you produce "bad" GTFS then it won't work as you think, but that it's not even clear how a certain rule should be interpreted.

I'm also not sure about this cumulativeness. It is the "old way" of doing things. In the past we all got used to that, that each time you entered a new vehicle you either had to use a new ticket or one of the tickets you already had validated. If the fares work that way in an agency then they will be fine even without enum=2. But maybe we should start to get used to look at it differently. As the rule anyway matches a sub-journey, you can look at it as the rule for calculating the fare prices for the sub-journey. And when we got used to the idea then we probably should think again about the enum and what it means for sub-journeys of more than 2 legs. And even changing the "formula" should not be a problem. It's not that we're changing something that's already in GTFS, we're only changing what's in the proposal.

I suppose that there's a reason for enum=2 being there, probably someone is producing data like that, so removing the functionality of being able to say "the price for the journey is the fare for the most expensive leg [plus $0.25 for each transfer]" makes no sense.

**Comment by omar-kabbani** [comment]
@flocsy would you be able to provide an example for these?

> 0: A + SUM(T) (this also clarifies something that is not 100% clear in the original way, that we mean to include only the 1st leg's fare as opposed to include all leg's fare except the last leg's)
1: SUM(L) + SUM(T)
2: MAX(L) + SUM(T)
3: SUM(T)

**Comment by flocsy** [comment]
@omar-kabbani what examples do you mean? These are the same cases written down with a different notation.

**Comment by omar-kabbani** [comment]
Okay, I think I initially misinterpreted your proposal - to make sure I got things right; 

0: A + SUM(T) [This means the first fare leg + current transfer cost]
1: SUM(L) + SUM(T) [This means the upcoming fare leg cost + current transfer cost]
2: MAX(L) + SUM(T) [This means the maximum cost of (past leg, upcoming leg) + current transfer cost] 
3: SUM(T) [This means only add the current transfer cost]

Is this correct?

**Comment by flocsy** [comment]
No.
0: A + SUM(T) - 2 leg: A + AB, 3 leg A + AB + BC - First leg fare + all transfer fares
1: SUM(L) + SUM(T) - 2 leg: A + AB + B, 3 leg: A + AB + B + BC + C - All leg fares + all transfer fares
2: MAX(L) + SUM(T) - 2 leg: MAX(A, B) + AB, 3 leg: MAX(A, B, C) + AB + BC - The most expensive leg fare + all transfer fares
3: SUM(T) - 2 leg: AB, 3 leg: AB + BC - All transfer fares

I like this discussion, because it shows perfectly how unclear the definitions are, and that we interpreted things differently. We should continue until it becomes much clearer!

**Comment by omar-kabbani** [comment]
Okay, I made an example to make sure that I get what you are describing with your proposed enumerations. I used the same example from my post above, except that the enumerations in `fare_transfer_rules.txt` correspond to what you are proposing. 

`fare_leg_rules.txt`

leg_group_id | from_area_id | to_area_id | network_id | amount | currency
-- | -- | -- | -- | -- | --
A | areaA | areaB | bus | 2 | CAD
B | areaB | areaC | bus | 0.5 | CAD
C | areaC | areaD | bus | 3 | CAD
D | areaD | areaE | bus | 1 | CAD
E | areaE | areaF | bus | 1.5 | CAD

`fare_transfer_rules.txt`

from_leg_group_id | to_leg_group_id | amount | currency | fare_transfer_type | spanning_limit | duration_limit | duration_limit_type
-- | -- | -- | -- | -- | -- | -- | --
A | B | 0.1 | CAD | 0 | 0 | 7200 | 0
B | C | 0.2 | CAD | 1 | 0 | 7200 | 0
C | D | 0.3 | CAD | 2 | 0 | 7200 | 0
D | E | 0.5 | CAD | 3 | 0 | 7200 | 0

Let's take trip A → B → C, since B → C is the last leg, then we consider its `fare_transfer_rule`. Since for that `fare_transfer_rule`, `enum=1`, then the cost is equal to all leg fares + all transfer fares
So, the cost will be A + AB + B + BC + C = 2 + 0.1 + 0.5 + 0.2 + 3 = 5.8 CAD

Another example: A → B → C → D, since C → D is the last leg, then we consider its `fare_transfer_rule`, which is `enum=2`. Then the cost is equal to the most expensive leg fare + all transfer fares
So the cost will be MAX (A, B, C, D) + AB + BC + CD = MAX(2, 0.5, 3, 1, 1.5) + 0.1 + 0.2 + 0.3 = 3 + 0.1 + 0.2 + 0.3 = 3.6 CAD

Is this a correct understanding of your proposal @flocsy?

**Comment by flocsy** [comment]
@omar-kabbani this is not what I meant. You interpretation seems to work by choosing the rule that matches the last transfer and applying it to all the previous transfers as well. This sounds to me contra-intuitive, especially because it contradicts the rule definition itself, because the last transfer rule should match from_leg_group_id:C, to_leg_group_id:D, so how can it be used for A->B and B->C?

In my opinion in order to be able to use enum=2 you need to have a rule that matches all the legs/transfers of the sub-journey. So if you want it to be able to match all 3 transfers then you'll need a transfer rule like:

fare_leg_rules:
leg_group_id: G, from_area_id: A, to_area_id: A, amount: 1
leg_group_id: G, from_area_id: A, to_area_id: B, amount: 1.5
leg_group_id: G, from_area_id: B, to_area_id: B, amount: 1
leg_group_id: G, from_area_id: B, to_area_id: C, amount: 1.5
leg_group_id: G, from_area_id: C, to_area_id: C, amount: 1
leg_group_id: G, from_area_id: C, to_area_id: D, amount: 2
leg_group_id: G, from_area_id: A, to_area_id: C, amount: 2
leg_group_id: G, from_area_id: A, to_area_id: D, amount: 2.5

fare_transfer_rules:
from_leg_group_id: G, to_leg_group_id: G, amount: 0.2, fare_transfer_type: 2

Now the areaA->areaB->areaC->areaD - meaning: l1: aA-aB, l2:aB-aC, l3: aC-aD - journey would all fall into 1 sub-journey, and the the transfer rule matches all 3 transfers, and makes it possible to use the rule for all transfers, and then the fare will be: MAX(1.5, 1.5, 2) + 0.2+0.2 = 2.40

This seems to be less of a problem with the other enum values, but because of the MAX(), enum=2 can only be used (logically) for the transfers of the same sub-journey that the rule "defines".

Maybe the best and easiest for now would be to remove enum=2, because if we keep it, it wouldn't be clear what it means for more than 2 legs, especially in a case like the one in your example, when (some of) the other legs in the sub-journey use different fare_transfer_type.

**Comment by omar-kabbani** [comment]
Sounds good - and thank you for the thorough explanation 
So the only change I will make to `fare_transfer_rules` is removing `enum=2`
